[
    "alacritty"
    "audacity"
    "beekeeper-studio"
    "blackhole-2ch"
    "blender"
    "backblaze"
    "discord"
    "gcloud-cli"
    "godot"
#   "grandperspective"
    "gitify"
    "superwhisper"
    "telegram"
    "microsoft-openjdk"
    "raspberry-pi-imager"
]