[
    "argo"
    "argocd"
    "awscli"
    "bitwarden-cli"
    "cargo-binstall"
    "cmake"
    "cocoapods"
    "colordiff"
    "diesel"
    "golangci-lint"
    "gst-libav"
    "gst-plugins-bad"
    "gst-plugins-base"
    "gst-plugins-good"
    "gst-plugins-ugly"
    "gstreamer"
    "idb-companion"
    "kustomize"
    "libyaml"
    # "nvm"
    # "node@24"
    "mobile-dev-inc/tap/maestro"
    "mysql-client@8.0"
    "ollama"
    "opencode"
    "openjdk"
    "opentofu"
    "oven-sh/bun/bun"
    "portaudio"
    "postgresql@14"
    "ruby"
    "rustup"
    "sentry-cli"
    "shellcheck"
    "stripe"
    # "vercel-cli"
    "watchman"
    "wget"
    "whisper-cpp"
    "yt-dlp"
    #"opencode"
#   "blackhole-2ch"
]
