[
    "argo"
    "difftastic"
    "docker-slim"
    "gcc" 
    "idb-companion"
    "colordiff"
    "mysql-client"
    "nvm"
    "libpq"
    "libyaml"
    "wget"
    "postgresql@14"
    "watchman"
    "whisper-cpp"
    # "microsoft-remote-desktop"
]