[
    "cargo-binstall"
    "cocoapods"
    "colordiff"
    "diesel"
    "libyaml"
    "mysql-client@8.0"
    "openjdk"
    "opentofu"
    "oven-sh/bun/bun"
    "postgresql@14"
    "ruby"
    "rustup"
    "watchman"
    "wget"
#    "argo"
#    "difftastic"
#    "docker-slim"
#    "gcc" 
#    "libpq"
#    "mysql-client"
#    "nvm"
#    "whisper-cpp"
#    # "microsoft-remote-desktop"
##    "idb-companion"
]
